DB_USERNAME: personal
DB_PASSWORD: personal
DB_HOST: 172.30.144.1
DB_PORT: 5434
DB_NAME: personal_db

server:
  port: 9997

GMAIL_USERNAME: kevintido0@gmail.com
GMAIL_PASSWORD: dfos dfta hwaj rbnr
EMAIL_SENDER: MicroService