DB_USERNAME: personal
DB_PASSWORD: personal
DB_HOST: 172.30.144.1
DB_PORT: 5434
DB_NAME: personal_db

server:
  port: 9997

GMAIL_USERNAME: kevintido0@gmail.com
GMAIL_PASSWORD: dfos dfta hwaj rbnr
EMAIL_SENDER: MicroService


MEDIA_SERVER_PATH: src/main/resources/filestorage/fullstack-medias/
MEDIA_BASE_URI: http://localhost:9997/media
MEDIA_CLIENT_PATH: /media/**