
spring:
  application:
    name: USER-SERVICE

  profiles:
    active: dev


  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#  eureka:
#    client:
#      register-with-eureka: true
#      fetch-registry: true
#      service-url:
#        defaultZone: http://localhost:8761/eureka/
#    instance:
#      hostname: localhost


  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    senderName: ${EMAIL_SENDER}
    default-encoding: UTF-8
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required: true
            enable: true
  client-path: /login/verify-email

  # token generation
  keys:
    access-private-token: keys/access-private
    access-public-token: keys/access-public
    refresh-private-token: keys/refresh-private
    refresh-public-token: keys/refresh-public



#  //  TODO: logs to see the issue that case
  logging:
    level:
      org.springframework.boot.context.config: DEBUG
      org.springframework.mail: DEBUG

  # image files
  media:
    server-path: ${MEDIA_SERVER_PATH}
    client-path: ${MEDIA_CLIENT_PATH}
    base-uri: ${MEDIA_BASE_URI}