
server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enable automatic route discovery from Eureka
    loadbalancer:
      retry:
        enabled: true  # Optional: Enables retrying failed requests

eureka:
  client:
    register-with-eureka: true   # API-Gateway should register itself with Eureka
    fetch-registry: true         # It should fetch the registry from Eureka Server
    service-url:
      defaultZone: http://localhost:8761/eureka/


#    routes:
#      - id: STUDENT-SERVICE
#        uri: lb://STUDENT-SERVICE
#        predicates:
#          - Path=/api/v1/student/**
#      - id: SCHOOL-SERVICE
#        uri: lb://SCHOOL-SERVICE
#        predicates:
#          - Path=/api/v1/school/**
#
#
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost

